name: Generate XML Sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    
    # 👇 ADD THIS LINE (THIS FIXES THE 403 ERROR)
    permissions:
      contents: write

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate the Sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://www.dekasirclasses.in/

    - name: Commit and Push the Sitemap
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml
        git commit -m "Automated sitemap update" || echo "No changes to commit"
        git push
